import type { StampConfig } from './types';

export const STAMP_TEMPLATES: StampConfig[] = [
  {
    id: 'normal',
    name: '기본',
    position: 'bottom-left',
    layout: 'vertical',
    timeFont: 'HelveticaNeue-CondensedBold, Helvetica Neue, sans-serif',
    dateFont: 'HelveticaNeue-CondensedBold, Helvetica Neue, sans-serif',
    timeSize: 36,
    dateSize: 28,
    timeColor: '#ffffff',
    dateColor: '#ffffff',
    shadowColor: 'rgba(0,0,0,0.35)',
    shadowRadius: 5,
    dateFormat: "yyyy'년' M'월' d'일' (ddd)",
    timeFormat: 'HH:mm',
    offsetX: 5.33,
    offsetY: 87.47,
  },
  {
    id: 'simple',
    name: '심플',
    position: 'bottom-center',
    layout: 'horizontal',
    timeFont: 'system-ui, sans-serif',
    dateFont: 'system-ui, sans-serif',
    timeSize: 42,
    dateSize: 42,
    timeColor: '#ffffff',
    dateColor: '#ffffff',
    shadowColor: 'rgba(0,0,0,0.35)',
    shadowRadius: 5,
    dateFormat: "yyyy'년' M'월' d'일' (ddd)",
    timeFormat: 'HH:mm',
    offsetX: 50,
    offsetY: 96.8,
  },
  {
    id: 'mini',
    name: '미니',
    position: 'bottom-right',
    layout: 'horizontal',
    timeFont: 'system-ui, sans-serif',
    dateFont: 'system-ui, sans-serif',
    timeSize: 22,
    dateSize: 22,
    timeColor: '#ffffff',
    dateColor: '#ffffff',
    shadowColor: 'rgba(0,0,0,0.35)',
    shadowRadius: 4,
    dateFormat: "yyyy'년' M'월' d'일' (ddd)",
    timeFormat: 'HH:mm',
    offsetX: 97.87,
    offsetY: 97.87,
  },
  {
    id: 'digital',
    name: '디지털',
    position: 'center',
    layout: 'horizontal',
    timeFont: 'TickingTimebombBB, sans-serif',
    dateFont: 'TickingTimebombBB, sans-serif',
    timeSize: 160,
    dateSize: 36,
    timeColor: '#ffffff',
    dateColor: '#ffffff',
    shadowColor: 'rgba(0,0,0,0.4)',
    shadowRadius: 6,
    dateFormat: "yyyy'년' M'월' d'일' (ddd)",
    timeFormat: 'HH:mm',
    offsetX: 50,
    offsetY: 50,
  },
  {
    id: 'slim01',
    name: '슬림',
    position: 'center',
    layout: 'split',
    timeFont: 'SpoqaHanSansNeo-Thin, SpoqaHanSans, sans-serif',
    dateFont: 'SpoqaHanSansNeo-Regular, SpoqaHanSans, sans-serif',
    timeSize: 80,
    dateSize: 18,
    timeColor: '#ffffff',
    dateColor: '#ffffff',
    shadowColor: 'rgba(0,0,0,0.3)',
    shadowRadius: 4,
    dateFormat: "yyyy'년' M'월' d'일' (ddd)",
    timeFormat: 'HH:mm',
    offsetX: 50,
    offsetY: 49,
  },
  {
    id: 'box',
    name: '박스',
    position: 'bottom-left',
    layout: 'vertical',
    timeFont: 'BlanchCaps, sans-serif',
    dateFont: 'BlanchCaps, sans-serif',
    timeSize: 56,
    dateSize: 44,
    timeColor: '#ffffff',
    dateColor: '#ffffff',
    shadowColor: 'rgba(0,0,0,0.35)',
    shadowRadius: 5,
    dateFormat: "yyyy'년' M'월' d'일' (ddd)",
    timeFormat: 'HH:mm',
    offsetX: 12.53,
    offsetY: 78.67,
    frame: 'box',
  },
];

export function getStampTemplate(id: string): StampConfig | undefined {
  return STAMP_TEMPLATES.find((t) => t.id === id);
}

export const DEFAULT_STAMP_ID = 'normal';
